### ISSUE TITLE
Newtonsoft version specification causes NU1603 warning

### ISSUE THREAD

**Issue by mikebridge** [plivo/plivo-dotnet#99]
I have this warning whenever I compile a netcore 2.0 assembly that references the plivo library:

```
Plivo 4.2.5 depends on Newtonsoft.Json (>= 10.0.0) but Newtonsoft.Json 10.0.0 was not found. An approximate best match of Newtonsoft.Json 10.0.1 was resolved.
```

I *think* this is because the `nuspec` file [specifies the dependency as `[10,)`](https://github.com/plivo/plivo-dotnet/blob/master/src/Plivo/Plivo.nuspec#L71), which effectively means "greater than or equal to 10.0.0.0".  However, [it tries 10.0.0.0 first](https://weblog.west-wind.com/posts/2014/Jun/19/Nuget-Dependencies-and-latest-Versions), and this [version does not exist](https://www.nuget.org/packages/Newtonsoft.Json/), hence the warning.

**Comment by mikebridge** [comment]
I can work around this by explicitly adding a reference to `Newtonsoft.Json`, but it would be nice if it didn't display the warning.

**Comment by huzaif-plivo** [comment]
@mikebridge This issue was resolved in the version 4.4.2, you can try our latest version 4.4.3.

**Comment by brutaldev** [comment]
`Plivo 4.4.10 depends on Newtonsoft.Json (>= 10.0.0) but Newtonsoft.Json 10.0.0 was not found`

Still getting it with v4.4.10.
